# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
