# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
