# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-26 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20170613_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
